title: Gareth's Musings
description: F#, Functional Programming and other musings are here.
author: Gareth Hubball
plugins:
  - jekyll-remote-theme

url: https://garethhubball.com
logo_url: assets/logo.png

remote_theme: heiswayi/the-plain
exclude: [.paket]